version: '3'
services:
  robot:
    build:
      context: ./
      dockerfile: docker/robot/Dockerfile
    container_name: robot
    env_file:
      - .env
    working_dir: /testes/
    volumes:
      - ./tests/Integration:/testes/
      - ./docker/robot/results:/report/
    network_mode: host
networks:
  maliin:
    driver: bridge
